// ─────────────────────────────────────────────────────────────────────────────
// Minimal, safe-by-default markdown → HTML renderer for blog post bodies.
//
// Why not pull in `marked` or `remark`? Our blog body source is either (a)
// LLM-generated by our own cron with a constrained prompt, or (b) edited by
// the site owner in admin. Both are trusted. We only need a small subset of
// markdown (headings, paragraphs, lists, links, images, code, bold/italic,
// blockquotes, horizontal rules, tables) and we want zero raw HTML to land on the
// page — so we escape first and only render the markdown features we support.
// ─────────────────────────────────────────────────────────────────────────────

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

// Inline formatting: bold, italic, code, links, images.
function inline(src: string): string {
  let out = src

  // images: ![alt](url)
  out = out.replace(/!\[([^\]]*)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_m, alt, url, title) => {
    const safeAlt = escapeHtml(alt || '')
    const safeUrl = escapeHtml(url)
    const safeTitle = title ? ` title="${escapeHtml(title)}"` : ''
    return `<img src="${safeUrl}" alt="${safeAlt}"${safeTitle} class="my-6 rounded-xl border border-white/5" loading="lazy" />`
  })

  // links: [text](url)
  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)(?:\s+"([^"]+)")?\)/g, (_m, text, url, title) => {
    const safeText = inline(text)
    const safeUrl = escapeHtml(url)
    const safeTitle = title ? ` title="${escapeHtml(title)}"` : ''
    const isExternal = /^https?:\/\//i.test(url) && !url.includes('listmyai.com')
    const target = isExternal ? ' target="_blank" rel="noopener noreferrer nofollow"' : ''
    return `<a href="${safeUrl}"${safeTitle} class="font-semibold text-red-400 underline-offset-4 hover:underline"${target}>${safeText}</a>`
  })

  // inline code: `code`
  out = out.replace(/`([^`]+)`/g, (_m, code) =>
    `<code class="rounded bg-white/10 px-1.5 py-0.5 font-mono text-[0.9em] text-amber-300">${escapeHtml(code)}</code>`
  )

  // bold (**text** or __text__)
  out = out.replace(/(\*\*|__)([^*_\n]+)\1/g, '<strong class="font-bold text-white">$2</strong>')

  // italic (*text* or _text_)
  out = out.replace(/(?:^|[^*])\*([^*\n]+)\*(?!\*)/g, m =>
    m.replace(/\*([^*\n]+)\*/, '<em class="text-slate-200">$1</em>')
  )

  return out
}

interface Block { type: string; content: string; level?: number; ordered?: boolean; items?: string[]; headers?: string[]; rows?: string[][] }

export function renderMarkdown(md: string): string {
  const lines = md.replace(/\r\n/g, '\n').split('\n')
  const blocks: Block[] = []
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    // Blank line
    if (!line.trim()) { i++; continue }

    // Fenced code: ```lang
    if (/^```/.test(line)) {
      const lang = line.slice(3).trim()
      const buf: string[] = []
      i++
      while (i < lines.length && !/^```/.test(lines[i])) { buf.push(lines[i]); i++ }
      i++ // skip closing fence
      blocks.push({ type: 'code', content: buf.join('\n'), level: 0 })
      void lang
      continue
    }

    // Heading: # to ######
    const h = line.match(/^(#{1,6})\s+(.+)$/)
    if (h) {
      blocks.push({ type: 'heading', level: h[1].length, content: h[2].trim() })
      i++; continue
    }

    // Horizontal rule
    if (/^---+$|^\*\*\*+$/.test(line.trim())) {
      blocks.push({ type: 'hr', content: '' })
      i++; continue
    }

    // Blockquote
    if (/^>\s?/.test(line)) {
      const buf: string[] = []
      while (i < lines.length && /^>\s?/.test(lines[i])) {
        buf.push(lines[i].replace(/^>\s?/, ''))
        i++
      }
      blocks.push({ type: 'quote', content: buf.join('\n') })
      continue
    }

    // Unordered list
    if (/^[-*+]\s+/.test(line)) {
      const items: string[] = []
      while (i < lines.length && /^[-*+]\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^[-*+]\s+/, ''))
        i++
      }
      blocks.push({ type: 'list', content: '', ordered: false, items })
      continue
    }

    // Ordered list
    if (/^\d+\.\s+/.test(line)) {
      const items: string[] = []
      while (i < lines.length && /^\d+\.\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\d+\.\s+/, ''))
        i++
      }
      blocks.push({ type: 'list', content: '', ordered: true, items })
      continue
    }

    // Table: | header | header | with | --- | separator |
    if (/^\s*\|/.test(line)) {
      const tableLines: string[] = []
      while (i < lines.length && /^\s*\|/.test(lines[i])) {
        tableLines.push(lines[i])
        i++
      }
      if (tableLines.length >= 2) {
        const headers = tableLines[0].split('|').map(h => h.trim()).filter(Boolean)
        const rows: string[][] = []
        for (let j = 2; j < tableLines.length; j++) {
          const cells = tableLines[j].split('|').map(c => c.trim()).filter(Boolean)
          if (cells.length === headers.length) rows.push(cells)
        }
        if (rows.length > 0) {
          blocks.push({ type: 'table', content: '', headers, rows })
          continue
        }
      }
      // Fallback: treat as paragraph if table parsing failed
      i = i - tableLines.length
    }

    // Paragraph: until blank line
    const buf: string[] = [line]
    i++
    while (i < lines.length && lines[i].trim() && !/^(#{1,6}\s|[-*+]\s|\d+\.\s|>|```)/.test(lines[i])) {
      buf.push(lines[i]); i++
    }
    blocks.push({ type: 'paragraph', content: buf.join(' ') })
  }

  // Render
  const headingSizes = ['', 'text-3xl mt-10 mb-4 font-black', 'text-2xl mt-10 mb-3 font-black', 'text-xl mt-8 mb-2 font-bold', 'text-lg mt-6 mb-2 font-bold', 'text-base mt-4 mb-1 font-bold', 'text-sm mt-4 mb-1 font-bold']

  const html = blocks.map(b => {
    switch (b.type) {
      case 'heading': {
        const size = headingSizes[b.level ?? 1] || headingSizes[1]
        const slug = (b.content || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80)
        return `<h${b.level} id="${slug}" class="text-white ${size}">${inline(b.content)}</h${b.level}>`
      }
      case 'paragraph':
        return `<p class="my-4 leading-relaxed text-slate-300">${inline(b.content)}</p>`
      case 'quote':
        return `<blockquote class="my-6 border-l-4 pl-4 italic text-slate-300" style="border-color:#e94560">${inline(b.content)}</blockquote>`
      case 'list': {
        const tag = b.ordered ? 'ol' : 'ul'
        const cls = b.ordered ? 'list-decimal' : 'list-disc'
        const items = (b.items ?? []).map(it => `<li class="my-1 leading-relaxed text-slate-300">${inline(it)}</li>`).join('')
        return `<${tag} class="my-4 space-y-1 pl-6 ${cls}">${items}</${tag}>`
      }
      case 'code':
        return `<pre class="my-6 overflow-x-auto rounded-xl border border-white/5 bg-black/40 p-4 text-sm font-mono text-slate-200"><code>${escapeHtml(b.content)}</code></pre>`
      case 'hr':
        return `<hr class="my-10 border-t" style="border-color:#1e2a3a" />`
      case 'table': {
        const headers = (b.headers ?? []).map(h => `<th class="px-4 py-2 text-left font-semibold text-white border-b" style="border-color:#1e2a3a">${inline(h)}</th>`).join('')
        const rows = (b.rows ?? []).map(row => {
          const cells = row.map(cell => `<td class="px-4 py-2 text-slate-300 border-b" style="border-color:#1e2a3a">${inline(cell)}</td>`).join('')
          return `<tr>${cells}</tr>`
        }).join('')
        return `<div class="my-6 overflow-x-auto rounded-xl border" style="border-color:#1e2a3a;background:#161b27"><table class="w-full"><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table></div>`
      }
      default:
        return ''
    }
  }).join('\n')

  return html
}

// Extract plain-text excerpt from markdown for meta descriptions.
export function plainExcerpt(md: string, maxLen = 180): string {
  const stripped = md
    .replace(/```[\s\S]*?```/g, '')
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
    .replace(/[#*_>`~-]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  return stripped.length > maxLen ? stripped.slice(0, maxLen).replace(/\s+\S*$/, '') + '…' : stripped
}
